Cdia pedro
ispc-programador2022/a6g2 pull request #21
Opened 2022-06-11 23:41 UTC by pedroispc

Agregar archivo funcion_suma

2022-06-12 00:30 UTC, seba-arok requested changes

2022-06-12 00:30 UTC, seba-arok commented on funcion_suma.py
> +    print(f"El resultado de la suma entre el parametro 1 y el parametro 2 es: {rtdo}")
Esta función tiene que devolver la suma de los dos números, se usa en otras funciones.

2022-06-12 23:36 UTC, pedroispc commented on funcion_suma.py
> +    print(f"El resultado de la suma entre el parametro 1 y el parametro 2 es: {rtdo}")
Gracias por la observación, el código fue modificado y espero que ahora este bien!

2022-06-12 23:39 UTC, seba-arok approved these changes

2022-06-12 23:39 UTC, seba-arok commented on funcion_suma.py
> +    return para1+para2
Genial 😁,  ya podes darle al botón verde de merge

2022-06-13 00:20 UTC, seba-arok approved these changes

2022-06-13 00:50 UTC, merged