13-cdia-111_fabian
ispc-programador2022/a6g2 pull request #22
Opened 2022-06-12 20:19 UTC by fabiang78

agregar archivo funciongenrnd

2022-06-12 20:34 UTC, seba-arok requested changes

2022-06-12 20:34 UTC, seba-arok commented on funciongenrnd.py
> +
Este método devuelve una lista de números, esos números que generaste con la función randint, se los tenes que guardar en una lista y retornar esa lista, no hace falta mostrarlos

2022-06-12 20:48 UTC, fabiang78 commented on funciongenrnd.py
> +
para modificar, lo descrago de nuevo?

2022-06-12 21:26 UTC, seba-arok commented on funciongenrnd.py
> +
no, no hace falta solo modificalo y hace un add, un commit y un push a tu rama, tampoco tenes que hacer un nuevo pull request, solo en la parte de  Reviewers, arriba a la derecha pedime review otra vez
![Screenshot 2022-06-12 182441](https://user-images.githubusercontent.com/106629805/173254275-a5b3038b-0f6b-4fed-b4cb-58a571278c1f.png)
En esas fechas circulares

2022-06-12 21:45 UTC, seba-arok requested changes

2022-06-12 21:45 UTC, seba-arok commented on funciongenrnd.py
> +        print( r.randint (0,100))
La definición de la lista esta bien, solo que la función devuelve una función vacía porque estas guardando los valores generados dentro de la lista, tenés que usar el la función append que tienen las listas para agregar el elemento
Asi,
my_list.append(r.randint(0,100)) 

el retoro esta bien
** la función no hace ningún print, no es la tarea de esta función mostrar la lista solo generarla y devolverla

2022-06-12 23:29 UTC, fabiang78 commented on funciongenrnd.py
> +
la verdad no tengo ni idea de lo que estoy haciendo. como puedo saber si la funcion esta bien si no imprime nada?

2022-06-12 23:33 UTC, seba-arok approved these changes

2022-06-12 23:33 UTC, seba-arok commented on funciongenrnd.py
> +
Genial 😁, fijate que debajo de cada uno de los mensaje que te escribi aparece algo como "resolve conversation", dale cada uno y después ya le podes dar al boton verde de marge que esta debajo para fusionar con dev

2022-06-12 23:36 UTC, seba-arok commented on funciongenrnd.py
> +
Lo consultas desde afuera, llamas a esa función y el print desde afuera, pones:

print(genrnd())

2022-06-12 23:36 UTC, seba-arok commented on funciongenrnd.py
> +
pero desde afuera y solo para probar no es parte de la función que tenés que construir

2022-06-13 00:39 UTC, JulianGrosso approved these changes

2022-06-16 01:53 UTC, merged